sudo: required
language: generic
services: 
  - docker

before_install: 
  - docker build -t matteodngh/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true matteodngh/docker-react npm run test